# Generated by Django 4.2.18 on 2025-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
